### ISSUE TITLE
(0, 0) or (null, null)

### ISSUE THREAD

**Issue by aniruddha-adhikary** [nuhil/bangladesh-geocode#15]
Thank you so much for your awesome work, really appreciate it.

I had an idea actually. What if the (0, 0) coordinates were replaced by (null, null)? Because (0, 0) actually refers to an actual location in the middle of oceans.

Since null means a value isn't present, maybe using null and making the fields nullable is a way to go?

**Comment by nuhil** [comment]
Thanks for your great suggestion @aniruddha-adhikary 
Will fix this some time or a pull request would be appreciated :)
