### ISSUE TITLE
Can not get word name or word name on the city corporation 

### ISSUE THREAD

**Issue by Tarequzzaman** [nuhil/bangladesh-geocode#22]
Hi,

I live in Dhaka Khelkhet Nikunja. In the JSON file, I can not get any option for this area. If there exists, pls help me.

**Comment by sakibbuddy** [comment]
Currently, it doesn't provide information regarding **city corporations** and the **ward**.

**Comment by Tarequzzaman** [comment]
Thanks for letting me know
