### ISSUE TITLE
কোনটা কার অধীন দিলে ভালো হতো। যেমন: ঢাকা বিভাগের অধীনের ঢাকা বিভাগের জেলাসমূহ...

### ISSUE THREAD

**Issue by Romjan-Ali** [nuhil/bangladesh-geocode#38]

**Comment by sakibbuddy** [comment]
You will find `division_id` field which indicates the division id from the division data.
For example, `{"id":"1","division_id":"1","name":"Comilla","bn_name":"কুমিল্লা","lat":"23.4682747","lon":"91.1788135","url":"www.comilla.gov.bd"}`

**Comment by nuhil** [comment]
Thank you @sakibbuddy
